feat: upgrade wordpress app to php 8.0

diff --git a/apps/wordpress/Dockerfile b/apps/wordpress/Dockerfile
--- a/apps/wordpress/Dockerfile
+++ b/apps/wordpress/Dockerfile
@@ -1,10 +1,42 @@
-FROM wordpress:php7.4-apache
+FROM wordpress:php8.0-apache
 WORKDIR /usr/src/wordpress
 RUN set -eux; \
 	find /etc/apache2 -name '*.conf' -type f -exec sed -ri -e "s!/var/www/html!$PWD!g" -e "s!Directory /var/www/!Directory $PWD!g" '{}' +; \
 	cp -s wp-config-docker.php wp-config.php
+
+# Copy uploads, custom themes and plugins into the image
 COPY ./wp-content/themes/. ./wp-content/themes/
 COPY ./wp-content/plugins/. ./wp-content/plugins/
 COPY ./wp-content/uploads/. ./wp-content/uploads/
-COPY ./wp-content/object-cache.php ./wp-content/object-cache.php
+
+# Install additional PHP extensions
+# See https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions
+RUN set -ex; \
+		apt-get update; \
+		apt-get install -y libgmp-dev; \
+		docker-php-ext-install -j "$(nproc)" gmp; \
+		docker-php-ext-enable gmp;
+# Set PHP.ini settings
+# See https://secure.php.net/manual/en/opcache.installation.php
 COPY custom.ini $PHP_INI_DIR/conf.d/
+RUN { \
+		echo 'opcache.memory_consumption=128'; \
+		echo 'opcache.interned_strings_buffer=8'; \
+		echo 'opcache.max_accelerated_files=4000'; \
+		echo 'opcache.revalidate_freq=2'; \
+		echo 'opcache.fast_shutdown=1'; \
+	} > $PHP_INI_DIR/conf.d/opcache-recommended.ini
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
+RUN { \
+# https://www.php.net/manual/en/errorfunc.constants.php
+# https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+		echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+		echo 'display_errors = Off'; \
+		echo 'display_startup_errors = Off'; \
+		echo 'log_errors = On'; \
+		echo 'error_log = /dev/stderr'; \
+		echo 'log_errors_max_len = 1024'; \
+		echo 'ignore_repeated_errors = On'; \
+		echo 'ignore_repeated_source = Off'; \
+		echo 'html_errors = Off'; \
+	} > $PHP_INI_DIR/conf.d/error-logging.ini
